package posra.dataaccess;

// Generated May 21, 2014 12:12:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Polymer generated by hbm2java
 */
public class Polymer implements java.io.Serializable {

	private Integer polymerId;
	private Segment segment;
	private String name;
	private Set externalIds = new HashSet(0);
	private Set segmentAssociations = new HashSet(0);

	public Polymer() {
	}

	public Polymer(Segment segment, String name) {
		this.segment = segment;
		this.name = name;
	}

	public Polymer(Segment segment, String name, Set externalIds,
			Set segmentAssociations) {
		this.segment = segment;
		this.name = name;
		this.externalIds = externalIds;
		this.segmentAssociations = segmentAssociations;
	}

	public Integer getPolymerId() {
		return this.polymerId;
	}

	public void setPolymerId(Integer polymerId) {
		this.polymerId = polymerId;
	}

	public Segment getSegment() {
		return this.segment;
	}

	public void setSegment(Segment segment) {
		this.segment = segment;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getExternalIds() {
		return this.externalIds;
	}

	public void setExternalIds(Set externalIds) {
		this.externalIds = externalIds;
	}

	public Set getSegmentAssociations() {
		return this.segmentAssociations;
	}

	public void setSegmentAssociations(Set segmentAssociations) {
		this.segmentAssociations = segmentAssociations;
	}

}
