package posra.dataaccess;

// Generated May 28, 2014 12:19:44 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Polymer generated by hbm2java
 */
public class Polymer implements java.io.Serializable {

	private Integer polymerId;
	private String name;
	private Set polymerRepeatUnitSegmentAssociations = new HashSet(0);
	private Set externalIds = new HashSet(0);
	private Set segmentAssociations = new HashSet(0);

	public Polymer() {
	}

	public Polymer(String name) {
		this.name = name;
	}

	public Polymer(String name, Set polymerRepeatUnitSegmentAssociations,
			Set externalIds, Set segmentAssociations) {
		this.name = name;
		this.polymerRepeatUnitSegmentAssociations = polymerRepeatUnitSegmentAssociations;
		this.externalIds = externalIds;
		this.segmentAssociations = segmentAssociations;
	}

	public Integer getPolymerId() {
		return this.polymerId;
	}

	public void setPolymerId(Integer polymerId) {
		this.polymerId = polymerId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPolymerRepeatUnitSegmentAssociations() {
		return this.polymerRepeatUnitSegmentAssociations;
	}

	public void setPolymerRepeatUnitSegmentAssociations(
			Set polymerRepeatUnitSegmentAssociations) {
		this.polymerRepeatUnitSegmentAssociations = polymerRepeatUnitSegmentAssociations;
	}

	public Set getExternalIds() {
		return this.externalIds;
	}

	public void setExternalIds(Set externalIds) {
		this.externalIds = externalIds;
	}

	public Set getSegmentAssociations() {
		return this.segmentAssociations;
	}

	public void setSegmentAssociations(Set segmentAssociations) {
		this.segmentAssociations = segmentAssociations;
	}

}
