package posra.dataaccess;

// Generated May 21, 2014 12:12:01 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * RepeatUnit generated by hbm2java
 */
public class RepeatUnit implements java.io.Serializable {

	private Integer repeatUnitId;
	private Segment segment;
	private Set segments = new HashSet(0);

	public RepeatUnit() {
	}

	public RepeatUnit(Segment segment) {
		this.segment = segment;
	}

	public RepeatUnit(Segment segment, Set segments) {
		this.segment = segment;
		this.segments = segments;
	}

	public Integer getRepeatUnitId() {
		return this.repeatUnitId;
	}

	public void setRepeatUnitId(Integer repeatUnitId) {
		this.repeatUnitId = repeatUnitId;
	}

	public Segment getSegment() {
		return this.segment;
	}

	public void setSegment(Segment segment) {
		this.segment = segment;
	}

	public Set getSegments() {
		return this.segments;
	}

	public void setSegments(Set segments) {
		this.segments = segments;
	}

}
