package posra.dataaccess;

// Generated May 27, 2014 2:46:51 PM by Hibernate Tools 4.0.0

/**
 * SegmentAssociationId generated by hbm2java
 */
public class SegmentAssociationId implements java.io.Serializable {

	private int segmentId1;
	private int segmentId2;
	private String relationshipType;
	private int polymerId;

	public SegmentAssociationId() {
	}

	public SegmentAssociationId(int segmentId1, int segmentId2,
			String relationshipType, int polymerId) {
		this.segmentId1 = segmentId1;
		this.segmentId2 = segmentId2;
		this.relationshipType = relationshipType;
		this.polymerId = polymerId;
	}

	public int getSegmentId1() {
		return this.segmentId1;
	}

	public void setSegmentId1(int segmentId1) {
		this.segmentId1 = segmentId1;
	}

	public int getSegmentId2() {
		return this.segmentId2;
	}

	public void setSegmentId2(int segmentId2) {
		this.segmentId2 = segmentId2;
	}

	public String getRelationshipType() {
		return this.relationshipType;
	}

	public void setRelationshipType(String relationshipType) {
		this.relationshipType = relationshipType;
	}

	public int getPolymerId() {
		return this.polymerId;
	}

	public void setPolymerId(int polymerId) {
		this.polymerId = polymerId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SegmentAssociationId))
			return false;
		SegmentAssociationId castOther = (SegmentAssociationId) other;

		return (this.getSegmentId1() == castOther.getSegmentId1())
				&& (this.getSegmentId2() == castOther.getSegmentId2())
				&& ((this.getRelationshipType() == castOther
						.getRelationshipType()) || (this.getRelationshipType() != null
						&& castOther.getRelationshipType() != null && this
						.getRelationshipType().equals(
								castOther.getRelationshipType())))
				&& (this.getPolymerId() == castOther.getPolymerId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSegmentId1();
		result = 37 * result + this.getSegmentId2();
		result = 37
				* result
				+ (getRelationshipType() == null ? 0 : this
						.getRelationshipType().hashCode());
		result = 37 * result + this.getPolymerId();
		return result;
	}

}
